export enum Color {
    RED = 'red',
    PINK = 'pink',
    PURPLE = 'purple',
    DEEP_PURPLE = 'deepPurple',
    INDIGO = 'indigo',
    BLUE = 'blue',
    LIGHT_BLUE = 'lightBlue',
    CYAN = 'cyan',
    TEAL = 'teal',
    GREEN = 'green',
    LIGHT_GREEN = 'lightGreen',
    LIME = 'lime',
    YELLOW = 'yellow',
    AMBER = 'amber',
    ORANGE = 'orange',
    DEEP_ORANGE = 'deepOrange',
    BROWN = 'brown',
    BLUE_GRAY = 'blueGray',
    GRAY = 'gray',
    PRIMARY = 'primary',
    SECONDARY = 'secondary',
    SUCCESS = 'success',
    DANGER = 'danger',
}

